packages:
  - "apps/**"
  - "packages/**"
  - "configs/**"

catalog:
  typescript: 5.7.3
  "@types/node": 22.13.4

catalogs:
  eslint:
    eslint: 9.20.1
    "@eslint/js": 9.20.0
    eslint-plugin-react: 7.37.4
    eslint-plugin-react-hooks: 5.1.0
    globals: 15.15.0
    prettier: 3.5.1
    prettier-plugin-tailwindcss: 0.6.11
    typescript-eslint: 8.24.0
  tailwind:
    tailwindcss: 4.0.6
    postcss: 8.5.2
  nestjs:
    "@nestjs/common": 11.0.10
    "@nestjs/core": 11.0.10
    "@nestjs/platform-express": 11.0.10
    "reflect-metadata": 0.2.2
    "@nestjs/cli": 11.0.3
    "@nestjs/schematics": 11.0.1
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": 19.0.10
    "@types/react-dom": 19.0.4
